# Generated by Django 5.0.4 on 2024-04-17 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_profile', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='admin_profile.adminprofile')),
                ('visitor', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='visitors.visitors')),
            ],
            options={
                'db_table': 'wishlist',
            },
        ),
    ]
