# Generated by Django 5.0.4 on 2024-04-17 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_profile', '0002_alter_adminprofile_category'),
        ('users', '0001_initial'),
        ('vendor_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='admin',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_profile.adminprofile'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='vendor',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_profile.vendorprofile'),
        ),
    ]
