# Generated by Django 5.0.4 on 2024-04-18 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stalls', '0003_alter_stalls_category'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.TextField(default='')),
                ('time', models.TextField(default='')),
                ('status', models.CharField(default='pending', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stall', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='stalls.stalls')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visitors.visitors')),
            ],
            options={
                'db_table': 'bookings',
            },
        ),
    ]
