# Generated by Django 5.0.4 on 2024-04-18 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='interest',
            field=models.TextField(default=''),
        ),
    ]
