# Generated by Django 5.0.4 on 2024-04-17 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('event_name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField(default='')),
                ('logo', models.TextField(default='')),
                ('catalog', models.CharField(max_length=255)),
                ('banner', models.CharField(default='', max_length=255)),
                ('DOB', models.TextField(default='')),
                ('start_date', models.TextField(default='')),
                ('end_date', models.TextField(default='')),
                ('price', models.TextField(default='')),
                ('whatsapp_no', models.TextField(default='')),
                ('social_links', models.TextField(default='')),
                ('status', models.IntegerField(default=0)),
                ('about', models.TextField(default='')),
                ('city', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.categories')),
            ],
            options={
                'db_table': 'admin_profile',
            },
        ),
    ]
