# Generated by Django 5.0.4 on 2024-04-17 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendor_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stalls',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stall_name', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('email', models.EmailField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('catalog', models.CharField(max_length=255)),
                ('banner', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('stall_visits', models.IntegerField(default=0)),
                ('rating', models.DecimalField(decimal_places=1, default=None, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_profile.vendorprofile')),
            ],
            options={
                'db_table': 'stalls',
            },
        ),
    ]
