# Generated by Django 5.0.4 on 2024-04-18 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('stalls', '0002_alter_stalls_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stalls',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='categories.categories'),
        ),
    ]
