# Generated by Django 5.0.4 on 2024-05-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitors',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
